app:
  name: My app
  description: welcome to ${app.name} updated
my:
  greeting: hello world thanga updated
  list.value: one,two,three updated
db:
  connection: "{connectionString: 'sdsfdf',userName: 'updated',password: 'updated'}"
  port: 9090
  host: 344.97
