app:
  name: dggdg
  description: dgdfg ${app.name} updated
my:
  greeting: hdgdfgdgd
  list.value: gdfgdfgd
db:
  connection: "{connectionString: 'test',userName: 'dgdgd',password: 'dgdf'}"
  port: 9090
  host: 344.97
